alias ga='git add'
alias gaa='git add .'
alias gbr='git branch'
alias gco='git checkout'
alias gcl='git clone'
alias gcm='git commit'
alias gcam='git commit -am'
alias gd='git diff'
alias gl='git l'
alias gl1='git l1'
alias glo='git lo'
alias glogg='git logg'
alias gps='git push'
alias gpl='git pull'
alias grm='git rm'
alias grmc='git rmc'
alias gst='git status'
alias gits='gst'

alias gut='git'
alias got='git'

